// apps/studio/src/components/editor/BottomPanel.tsx
import { useEffect, useState } from "react";
import { ChevronUp, ChevronDown, Loader2, RefreshCw, Trash2, Zap } from "lucide-react";
import { useWorkflow } from "@/lib/workflow-context";
import { api } from "@/lib/api";
import { ErrorBoundary } from "@/lib/error-boundary";

const TABS = ["Logs", "Results", "Memory", "Datasets", "Activity", "History"] as const;
type Tab = (typeof TABS)[number];

export function BottomPanel() {
  const { logs, dispatch, nodes } = useWorkflow();
  const [tab, setTab] = useState<Tab>("Logs");
  const [open, setOpen] = useState(true);

  return (
    <ErrorBoundary>
    <div className={`shrink-0 border-t border-border bg-surface ${open ? "h-56" : "h-9"} flex flex-col transition-all`}>
      <div className="flex h-9 items-center border-b border-border pr-2">
        <div className="flex">
          {TABS.map((t) => (
            <button
              key={t}
              onClick={() => {
                setTab(t);
                setOpen(true);
              }}
              className={`relative px-4 py-2 text-xs font-semibold transition ${
                tab === t && open ? "text-primary" : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {t}
              {tab === t && open && <span className="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-primary" />}
            </button>
          ))}
        </div>
        <div className="ml-auto flex items-center gap-1">
          {open && tab === "Logs" && (
            <button
              onClick={() => dispatch({ type: "clear_logs" })}
              className="rounded p-1 text-muted-foreground hover:bg-accent hover:text-foreground"
              title="Clear"
            >
              <Trash2 className="h-3.5 w-3.5" />
            </button>
          )}
          <button onClick={() => setOpen(!open)} className="rounded p-1 text-muted-foreground hover:bg-accent">
            {open ? <ChevronDown className="h-3.5 w-3.5" /> : <ChevronUp className="h-3.5 w-3.5" />}
          </button>
        </div>
      </div>

      {open && (
        <div className="scrollbar-thin flex-1 overflow-y-auto px-3 py-2">
          {tab === "Logs" && <LogsTab logs={logs} />}
          {tab === "Results" && <ResultsTab nodes={nodes} />}
          {tab === "Memory" && <MemoryTab />}
          {tab === "Datasets" && <DatasetsTab />}
          {tab === "Activity" && <ActivityTab active={tab === "Activity"} />}
          {tab === "History" && <HistoryTab />}
        </div>
      )}
    </div>
    </ErrorBoundary>
  );
}

function LogsTab({ logs }: { logs: ReturnType<typeof useWorkflow>["logs"] }) {
  if (logs.length === 0) {
    return <Empty>No logs yet — press Run to execute the workflow.</Empty>;
  }
  return (
    <div className="space-y-1 font-mono text-[12px]">
      {logs.map((l) => (
        <div key={l.id} className="flex items-start gap-2 rounded px-2 py-1 hover:bg-surface-container">
          <span className="shrink-0 text-muted-foreground">[{l.ts}]</span>
          <span
            className={
              l.level === "success"
                ? "text-success"
                : l.level === "error"
                  ? "text-danger"
                  : l.level === "llm"
                    ? "text-warning"
                    : l.level === "debug"
                      ? "text-info"
                      : "text-foreground"
            }
          >
            [{l.level.toUpperCase()}]
          </span>
          <span className="flex-1 break-words text-foreground/90">{l.message}</span>
        </div>
      ))}
    </div>
  );
}

function ResultsTab({ nodes }: { nodes: ReturnType<typeof useWorkflow>["nodes"] }) {
  const results = nodes.filter((n) => n.config?.output);
  if (results.length === 0) {
    return <Empty>No results yet. Run a workflow to see outputs.</Empty>;
  }
  return (
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
      {results.map((n) => (
        <div key={n.id} className="rounded-md border border-border bg-surface-container p-3">
          <div className="mb-1 flex items-center justify-between text-xs">
            <span className="font-semibold">{n.type}</span>
            <span
              className={`rounded-full px-1.5 py-0.5 text-[9px] font-bold uppercase ${
                n.status === "error" ? "bg-danger/15 text-danger" : "bg-success/15 text-success"
              }`}
            >
              {n.status ?? "idle"}
            </span>
          </div>
          <p className="text-[11px] text-muted-foreground line-clamp-2">{String(n.config?.output || "").slice(0, 120)}</p>
        </div>
      ))}
    </div>
  );
}

function DatasetsTab() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    api.getDatasetStats()
      .then(setData)
      .catch(() => setData(null))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <Loading />;
  if (!data || !data.datasets || data.datasets.length === 0) {
    return <Empty>No datasets found.</Empty>;
  }
  return (
    <div className="space-y-2">
      <div className="mb-2 grid grid-cols-3 gap-2">
        <StatBox label="Total Interactions" value={data.totalInteractions ?? "—"} />
        <StatBox label="Claim Count" value={data.claimCount ?? "—"} />
        <StatBox label="Privacy Score" value={data.privacyScore ? `${data.privacyScore}/100` : "—"} />
      </div>
      {data.datasets.map((ds: any, i: number) => (
        <div key={i} className="flex items-center justify-between rounded-md border border-border bg-surface-container px-3 py-2 text-xs">
          <span className="font-semibold">{ds.category || ds.name || `Dataset ${i + 1}`}</span>
          <span className="text-muted-foreground">
            {ds.claimCount ?? ds.size ?? 0} claims
            {ds.privacyScore != null && <span className="ml-2 text-success">{ds.privacyScore}/100</span>}
          </span>
        </div>
      ))}
    </div>
  );
}

function ActivityTab({ active }: { active: boolean }) {
  const { selectedAgentId } = useWorkflow();
  const [activityEntries, setActivityEntries] = useState<any[]>([]);
  const [activityLoading, setActivityLoading] = useState(false);

  const loadActivity = async () => {
    if (!selectedAgentId) return;
    setActivityLoading(true);
    try {
      const res = await fetch(`/api/v1/agents/${selectedAgentId}/activity`);
      const entries = await res.json();
      setActivityEntries(entries || []);
    } catch { setActivityEntries([]); }
    finally { setActivityLoading(false); }
  };

  useEffect(() => { if (active) loadActivity(); }, [active, selectedAgentId]);

  if (!selectedAgentId) {
    return <Empty>Select an agent to view activity</Empty>;
  }
  if (activityLoading) return <Loading />;
  if (activityEntries.length === 0) {
    return <Empty>No activity for this agent</Empty>;
  }
  return (
    <div className="space-y-1.5">
      {activityEntries.map((entry: any) => (
        <div key={entry.id} className="rounded-md border border-border bg-surface-container px-2.5 py-1.5 text-xs">
          <div className="flex items-center justify-between">
            <span className="font-medium text-foreground">{entry.action}</span>
            <span className="text-[10px] text-muted-foreground">{new Date(entry.created_at).toLocaleTimeString()}</span>
          </div>
          <div className="mt-0.5 text-muted-foreground">
            {entry.protocol} · {entry.amount_spent} mist
            {entry.tx_digest && (
              <a href={`https://suiscan.xyz/testnet/tx/${entry.tx_digest}`} target="_blank" className="ml-1 text-primary hover:underline">View</a>
            )}
          </div>
        </div>
      ))}
    </div>
  );
}

function HistoryTab() {
  const { dispatch } = useWorkflow();
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const load = () => {
    setLoading(true);
    api.listExecutionHistory()
      .then((data) => setItems(data || []))
      .catch(() => setItems([]))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  if (loading) return <Loading />;
  if (items.length === 0) {
    return (
      <div className="grid h-full place-items-center">
        <div className="text-center">
          <p className="text-xs text-muted-foreground mb-2">No execution history.</p>
          <button
            onClick={load}
            className="inline-flex items-center gap-1 rounded-md border border-border bg-surface-container px-3 py-1.5 text-xs hover:bg-accent"
          >
            <RefreshCw className="h-3 w-3" /> Refresh
          </button>
        </div>
    </div>
  );
  }
  return (
    <div className="space-y-2">
      {items.map((entry) => (
        <div key={entry.id || entry.run_id} className="rounded-md border border-border bg-surface-container p-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span
                className={`inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${
                  entry.status === "completed"
                    ? "bg-success/15 text-success"
                    : entry.status === "failed"
                      ? "bg-danger/15 text-danger"
                      : "bg-warning/15 text-warning"
                }`}
              >
                {entry.status || "unknown"}
              </span>
              <span className="text-xs font-semibold text-foreground">{entry.workflow_name || entry.name || "Workflow"}</span>
            </div>
            <div className="flex items-center gap-2">
              {entry.run_duration_ms != null && (
                <span className="text-[10px] text-muted-foreground">{entry.run_duration_ms}ms</span>
              )}
              <button
                onClick={() => {
                  if (entry.workflow_id) {
                    dispatch({ type: "log", entry: { id: `l_${Date.now()}`, level: "info", message: `Loading workflow ${entry.workflow_id}...`, ts: new Date().toTimeString().slice(0, 8) } });
                  }
                }}
                className="rounded bg-primary/15 px-2 py-0.5 text-[10px] font-semibold text-primary hover:bg-primary/25"
              >
                Re-run
              </button>
            </div>
          </div>
          {entry.started_at && (
            <div className="mt-1 text-[10px] text-muted-foreground">
              {new Date(entry.started_at).toLocaleString()}
            </div>
          )}
          {entry.error_message && (
            <div className="mt-1 text-[10px] text-danger">{entry.error_message}</div>
          )}
        </div>
      ))}
    </div>
  );
}

function MemoryTab() {
  const [poolName, setPoolName] = useState("");
  const [results, setResults] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const search = async () => {
    const name = poolName.trim();
    if (!name) return;
    setLoading(true);
    setError("");
    try {
      const data = await api.searchMemory(name);
      setResults(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Search failed");
      setResults(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-3">
      <div className="flex gap-2">
        <input
          value={poolName}
          onChange={(e) => setPoolName(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && search()}
          placeholder="Pool name..."
          className="h-8 flex-1 rounded-md border border-border bg-surface-container px-2.5 text-xs outline-none focus:ring-2 focus:ring-ring"
        />
        <button
          onClick={search}
          disabled={loading || !poolName.trim()}
          className="rounded-md bg-primary px-3 py-1 text-xs font-semibold text-primary-foreground hover:opacity-90 disabled:opacity-40"
        >
          {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : "Search"}
        </button>
      </div>
      {error && <div className="rounded-md bg-danger/10 px-3 py-2 text-xs text-danger">{error}</div>}
      {results && !loading && (
        <div className="rounded-md border border-border bg-surface-container p-3">
          <pre className="text-[11px] font-mono whitespace-pre-wrap break-words text-muted-foreground">
            {JSON.stringify(results, null, 2)}
          </pre>
        </div>
      )}
      {!results && !loading && !error && (
        <p className="text-xs text-muted-foreground">Enter a pool name to search cross-workflow memory.</p>
      )}
    </div>
  );
}

function StatBox({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="rounded-md border border-border bg-surface-container p-2 text-center">
      <div className="text-sm font-bold text-foreground">{value}</div>
      <div className="text-[10px] text-muted-foreground">{label}</div>
    </div>
  );
}

function Loading() {
  return (
    <div className="grid h-full place-items-center">
      <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
    </div>
  );
}

function Empty({ children }: { children: React.ReactNode }) {
  return <div className="grid h-full place-items-center text-xs text-muted-foreground">{children}</div>;
}

// apps/studio/src/app/layout/bottom-panel.component.ts
import { Component, inject, input, output, signal } from '@angular/core';
import { NgClass, DatePipe } from '@angular/common';
import type { LogEntry, WorkflowExecutionResult } from '../shared/types';
import { ApiService } from '../shared/api.service';

@Component({
  selector: 'app-bottom-panel',
  standalone: true,
  imports: [NgClass, DatePipe],
  template: `
    <div
      class="flex flex-col border-t border-harbor-border bg-harbor-surface transition-all"
      [class.h-48]="expanded()"
      [class.h-8]="!expanded()"
    >
      <button
        (click)="toggleExpanded()"
        class="flex h-8 items-center gap-2 border-b border-harbor-border px-4 text-xs font-medium text-harbor-text-muted transition-colors hover:text-harbor-text-heading"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          class="transition-transform"
          [class.rotate-180]="expanded()"
        >
          <polyline points="18 15 12 9 6 15"/>
        </svg>
        {{ expanded() ? 'Hide' : 'Show' }} Panel
      </button>

      @if (expanded()) {
        <div class="flex border-b border-harbor-border">
          @for (tab of tabs; track tab.key) {
            <button
              (click)="activeTab.set(tab.key)"
              class="px-4 py-1.5 text-xs font-medium transition-colors"
              [class.text-harbor-text-heading]="activeTab() === tab.key"
              [class.border-b-2]="activeTab() === tab.key"
              [class.border-walrus-400]="activeTab() === tab.key"
              [class.text-harbor-text-muted]="activeTab() !== tab.key"
            >
              {{ tab.label }}
            </button>
          }
        </div>

        <div class="flex-1 overflow-y-auto p-3">
          @if (activeTab() === 'logs') {
            <div class="space-y-1">
              @for (log of executionLogs(); track log.timestamp) {
                <div
                  class="flex items-start gap-3 rounded-lg border-l-2 px-3 py-2 text-xs"
                  [class.border-blue-500]="log.type === 'info'"
                  [class.border-red-500]="log.type === 'error'"
                  [class.border-amber-500]="log.type === 'llm'"
                  [class.border-indigo-500]="log.type === 'recall'"
                  [class.border-green-500]="log.type === 'remember'"
                >
                  <div class="flex-1">
                    <div class="text-harbor-text-body">{{ log.message }}</div>
                    <div class="mt-0.5 text-harbor-text-muted">{{ log.nodeLabel }} &middot; {{ log.timestamp | date:'HH:mm:ss' }}</div>
                  </div>
                </div>
              } @empty {
                <div class="py-8 text-center text-sm text-harbor-text-muted">No logs yet. Run a workflow to see execution logs.</div>
              }
            </div>
          }

          @if (activeTab() === 'results') {
            <div class="space-y-2">
              @for (result of executionResults(); track result.timestamp) {
                <div class="rounded-lg border border-harbor-border bg-harbor-card-bg p-3">
                  <div class="flex items-center gap-2">
                    <span
                      class="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium uppercase"
                      [ngClass]="{
                        'bg-green-500/20 text-green-400': result.status === 'success',
                        'bg-red-500/20 text-red-400': result.status === 'error'
                      }"
                    >
                      {{ result.status }}
                    </span>
                    <span class="text-xs font-medium text-harbor-text-heading">{{ result.nodeLabel }}</span>
                  </div>
                  <div class="mt-1 text-xs text-harbor-text-secondary">{{ result.output }}</div>
                </div>
              } @empty {
                <div class="py-8 text-center text-sm text-harbor-text-muted">No results yet.</div>
              }
            </div>
          }

          @if (activeTab() === 'memory') {
            <div class="flex gap-2 mb-3">
              <input
                type="text"
                placeholder="Pool name to search..."
                class="flex-1 rounded border border-harbor-border bg-harbor-card-bg px-3 py-1.5 text-xs text-harbor-text-body placeholder:text-harbor-text-muted outline-none focus:border-walrus-400"
                [value]="memoryQuery()"
                (input)="memoryQuery.set($any($event.target).value)"
                (keydown.enter)="searchMemory()"
              />
              <button
                (click)="searchMemory()"
                class="rounded bg-walrus-500 px-3 py-1.5 text-xs font-medium text-white transition-colors hover:bg-walrus-600"
              >
                Search Memory
              </button>
            </div>
            @if (isSearching()) {
              <div class="text-xs text-harbor-text-muted">Searching...</div>
            } @else if (memoryResultContext()) {
              <div class="rounded-lg border border-harbor-border bg-harbor-card-bg p-3 text-xs text-harbor-text-body whitespace-pre-wrap">{{ memoryResultContext() }}</div>
            } @else if (memoryQuery()) {
              <div class="py-4 text-center text-xs text-harbor-text-muted">No results found.</div>
            } @else {
              <div class="py-8 text-center text-sm text-harbor-text-muted">
                Enter a pool name above to explore shared agent memory.
              </div>
            }
          }

          @if (activeTab() === 'datasets') {
            <div class="space-y-2">
              @if (datasets().length === 0 && !isLoadingDatasets()) {
                <button (click)="loadDatasets()" class="w-full rounded-lg bg-harbor-control-bg px-3 py-2 text-xs text-harbor-text-body hover:bg-harbor-control-hover">
                  Load Datasets
                </button>
              }
              @if (isLoadingDatasets()) {
                <div class="text-xs text-harbor-text-muted">Loading...</div>
              }
              @for (ds of datasets(); track ds.id) {
                <div class="rounded-lg border border-harbor-border bg-harbor-card-bg p-3">
                  <div class="flex items-center justify-between">
                    <span class="text-xs font-medium text-harbor-text-heading">{{ ds.category }}</span>
                    <span class="text-[10px] text-harbor-text-muted">{{ ds.claimCount }} claims</span>
                  </div>
                  <div class="mt-1 text-xs text-harbor-text-secondary">{{ ds.sourceDomain }} &middot; {{ ds.sampleSize }} samples</div>
                  <div class="mt-1 flex items-center gap-2">
                    <span
                      class="text-[10px]"
                      [class.text-green-400]="ds.privacyScore >= 95"
                      [class.text-amber-400]="ds.privacyScore < 95"
                    >
                      Privacy: {{ ds.privacyScore }}/100
                    </span>
                  </div>
                </div>
              }
            </div>
          }

          @if (activeTab() === 'activity') {
            <div class="space-y-2">
              @if (activityEntries().length === 0) {
                <button (click)="loadActivity()" class="w-full rounded-lg bg-harbor-control-bg px-3 py-2 text-xs text-harbor-text-body hover:bg-harbor-control-hover">Load Activity</button>
              }
              @for (entry of activityEntries(); track entry.id) {
                <div class="rounded-lg border border-harbor-border bg-harbor-card-bg px-3 py-2 text-xs">
                  <div class="flex items-center justify-between">
                    <span class="text-harbor-text-heading">{{ entry.action }}</span>
                    <span class="text-harbor-text-muted">{{ entry.created_at | date:'short' }}</span>
                  </div>
                  <div class="text-harbor-text-secondary">{{ entry.protocol }} &middot; {{ entry.amount_spent }} mist</div>
                </div>
              }
            </div>
          }

          @if (activeTab() === 'history') {
            <div class="space-y-2">
              @if (executionHistory().length === 0 && !isLoadingHistory()) {
                <button (click)="loadHistory()" class="w-full rounded-lg bg-harbor-control-bg px-3 py-2 text-xs text-harbor-text-body hover:bg-harbor-control-hover">Load History</button>
              }
              @if (isLoadingHistory()) {
                <div class="text-xs text-harbor-text-muted">Loading...</div>
              }
              @for (entry of executionHistory(); track entry.id) {
                <div class="rounded-lg border border-harbor-border bg-harbor-card-bg p-3">
                  <div class="flex items-center justify-between">
                    <div class="flex items-center gap-2">
                      <span
                        class="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium uppercase"
                        [ngClass]="{
                          'bg-green-500/20 text-green-400': entry.status === 'completed',
                          'bg-red-500/20 text-red-400': entry.status === 'failed',
                          'bg-amber-500/20 text-amber-400': entry.status !== 'completed' && entry.status !== 'failed'
                        }"
                      >
                        {{ entry.status }}
                      </span>
                      <span class="text-xs font-medium text-harbor-text-heading">{{ entry.workflow_name }}</span>
                    </div>
                    <div class="flex items-center gap-2">
                      <span class="text-[10px] text-harbor-text-muted">{{ entry.run_duration_ms }}ms</span>
                      <button
                        (click)="rerunWorkflow.emit(entry.workflow_id)"
                        class="rounded bg-walrus-500 px-2 py-0.5 text-[10px] font-medium text-white transition-colors hover:bg-walrus-600"
                      >
                        Re-run
                      </button>
                    </div>
                  </div>
                  <div class="mt-1 text-[10px] text-harbor-text-muted">{{ entry.started_at | date:'short' }}</div>
                  @if (entry.error_message) {
                    <div class="mt-1 text-[10px] text-red-400">{{ entry.error_message }}</div>
                  }
                </div>
              }
            </div>
          }
        </div>
      }
    </div>
  `,
})
export class BottomPanelComponent {
  private api = inject(ApiService);
  executionLogs = input<LogEntry[]>([]);
  executionResults = input<WorkflowExecutionResult[]>([]);
  nodeStates = input<Record<string, string>>({});
  agentId = input<string | null>(null);
  expanded = signal(false);
  activeTab = signal<'logs' | 'results' | 'memory' | 'datasets' | 'activity' | 'history'>('logs');
  memoryQuery = signal('');
  memoryResultContext = signal('');
  isSearching = signal(false);
  datasets = signal<any[]>([]);
  isLoadingDatasets = signal(false);
  activityEntries = signal<any[]>([]);
  executionHistory = signal<any[]>([]);
  isLoadingHistory = signal(false);
  rerunWorkflow = output<string>();

  toggleExpanded() {
    this.expanded.update(v => !v);
  }

  async searchMemory() {
    const poolName = this.memoryQuery().trim();
    if (!poolName) return;
    this.isSearching.set(true);
    this.memoryResultContext.set('');
    try {
      const result: any = await this.api.fetchMemoryLogs(poolName);
      this.memoryResultContext.set(result.context || 'No results.');
    } catch {
      this.memoryResultContext.set('Failed to fetch memory. Check the pool name.');
    } finally {
      this.isSearching.set(false);
    }
  }

  async loadDatasets() {
    this.isLoadingDatasets.set(true);
    try {
      const res = await fetch('/api/v1/datasets');
      const data = await res.json();
      this.datasets.set(data.datasets || []);
    } catch {
      this.datasets.set([]);
    } finally {
      this.isLoadingDatasets.set(false);
    }
  }

  async loadHistory() {
    this.isLoadingHistory.set(true);
    try {
      const res = await fetch('/api/v1/execute/history');
      const data = await res.json();
      this.executionHistory.set(data || []);
    } catch {
      this.executionHistory.set([]);
    } finally {
      this.isLoadingHistory.set(false);
    }
  }

  async loadActivity() {
    const id = this.agentId();
    if (!id) return;
    try {
      const entries = await this.api.getAgentActivity(id);
      this.activityEntries.set(entries);
    } catch {
      this.activityEntries.set([]);
    }
  }

  tabs = [
    { key: 'logs' as const, label: 'Execution Logs' },
    { key: 'results' as const, label: 'Results' },
    { key: 'memory' as const, label: 'Memory Explorer' },
    { key: 'datasets' as const, label: 'Datasets' },
    { key: 'activity' as const, label: 'Activity' },
    { key: 'history' as const, label: 'History' },
  ];
}
